### PR TITLE
fix(elevenlabs): fix errors capturing frames

### LINKED ISSUE #270: `InvalidState - failed to capture frame` happening sporadically for 11Labs TTS
## Description

As reported on the Slack Livekit Community, sometimes an error occurs causing the Livekit Agent to fail when using the 11Labs TTS service.

## Log trace

```
[14:20:06.066] WARN (51915): new playout while the source is still playing
    speechId: "77be5998-d0ee-4aa7-b733-769d09f88b36"
    queuedDuration: 8
Duration: 60.001 seconds.
Checking credit balance...
Participant user-dvvhnj65jrjp0v7fa4ga is connected to the room.
Participant has enough credit to continue.
[14:20:16.597] WARN (51915): new playout while the source is still playing
    speechId: "98e2c4d3-be81-4561-b807-5714a4a1af5c"
    queuedDuration: 18
/Users/auringali/Desktop/LF/voices-ai-conversation-server/node_modules/.pnpm/@livekit+rtc-node@0.12.2/node_modules/@livekit/rtc-node/src/audio_source.ts:134
      throw new Error(cb.error);
            ^


Error: an RtcError occured: InvalidState - failed to capture frame
    at AudioSource.captureFrame (/Users/auringali/Desktop/LF/voices-ai-conversation-server/node_modules/.pnpm/@livekit+rtc-node@0.12.2/node_modules/@livekit/rtc-node/src/audio_source.ts:134:13)
    at async <anonymous> (/Users/auringali/Desktop/LF/voices-ai-conversation-server/node_modules/.pnpm/@livekit+agents@0.6.0_@livekit+rtc-node@0.12.2/node_modules/@livekit/agents/src/pipeline/agent_playout.ts:162:11)

Node.js v23.1.0
[14:20:17.277] WARN (51852): job process exited unexpectedly
    err: {
      "type": "Error",
      "message": "Channel closed",
      "stack":
          Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
              at target.send (node:internal/child_process:753:16)
              at Timeout._onTimeout (/Users/auringali/Desktop/LF/voices-ai-conversation-server/node_modules/.pnpm/@livekit+agents@0.6.0_@livekit+rtc-node@0.12.2/node_modules/@livekit/agents/dist/ipc/proc_job_executor.js:47:18)
              at listOnTimeout (node:internal/timers:614:17)
              at process.processTimers (node:internal/timers:549:7)
      "code": "ERR_IPC_CHANNEL_CLOSED"
    }
```

### PR DESCRIPTION
**Pull request by nbsp**
the error seems to have been with Node.js array buffer handling. copying the implementation from the newer Cartesia plugin seems to work wonders, though i'm unsure if that's because it's fixed or because i couldn't come across the issue; it's a weird one to reproduce.

drive-by removed flake.* and .envrc as i don't use nix anymore

closes #270

### CODE REVIEW

File: plugins/elevenlabs/src/tts.ts [hunk 1]
```diff
@@ -278,6 +278,12 @@ export class SynthesizeStream extends tts.SynthesizeStream {
                 lastFrame = frame;
               }
               sendLastFrame(segmentId, true);
+              this.queue.put(SynthesizeStream.END_OF_STREAM);
+
+              if (segmentId === requestId) {
+                ws.close();
```
Comment (lukasIO) [inline plugins/elevenlabs/src/tts.ts:284]: what happens to the ws connection if this condition is not true?

Comment (nbsp) [reply plugins/elevenlabs/src/tts.ts:284]: then it will keep going. END_OF_STREAM is just the end of the current utterance. this close is just making sure on our end that the connection closes when it needs to, even though it should be closed on the provider's end

Comment (lukasIO) [reply plugins/elevenlabs/src/tts.ts:284]: got it, thanks!

**Review by lukasIO — APPROVED** [review]
