### PR TITLE
fix(stt): gracefully fail on StreamAdapter errors

### LINKED ISSUE #273: Process fails on `APIConnectionError: Connection error` for STT service (`OpenAI.withGroq`)
We got a `ERR_IPC_CHANNEL_CLOSED` error caused by a 500 error coming back from the STT service on Groq.
Such API errors may happen once in a while and it would be nice to be able to recover from these errors / informing the user about these errors in some way with a callback, rather than the process shutting down entirely.

```
2025-01-23 11:39:05.938	
{"log":"/app/node_modules/.pnpm/openai@4.79.4_ws@8.18.0_zod@3.24.1/node_modules/openai/src/core.ts:480","source":"stderr"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"Node.js v20.18.2"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":""}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"}"}
2025-01-23 11:39:05.939	
{"log":"  }","source":"stderr"}
2025-01-23 11:39:05.939	
{"log":"    code: 'ECONNRESET'","source":"stderr"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"    errno: 'ECONNRESET',"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"    type: 'system',"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"      at emitErrorCloseNT (node:internal/streams/destroy:128:3)"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"      at emitErrorNT (node:internal/streams/destroy:169:8)"}
2025-01-23 11:39:05.939	
{"log":"      at TLSSocket.emit (node:events:530:35)","source":"stderr"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"      at TLSSocket.socketErrorListener (node:_http_client:504:5)"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"      at emitErrorEvent (node:_http_client:101:11)"}
2025-01-23 11:39:05.939	
{"log":"      at ClientRequest.emit (node:events:518:28)","source":"stderr"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"      at ClientRequest.<anonymous> (/app/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"  cause: FetchError: request to https://api.groq.com/openai/v1/audio/transcriptions failed, reason: read ECONNRESET"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"  type: undefined,"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"  param: undefined,"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"  code: undefined,"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"  error: undefined,"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"  request_id: undefined,"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"  headers: undefined,"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"  status: undefined,"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"    at async Promise.all (index 1) {"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"    at async recognize (/app/node_modules/.pnpm/@livekit+agents@0.6.3_patch_hash=eq3w7j4u37gz34omjmrey44zca_@livekit+rtc-node@0.13.2/node_modules/@livekit/agents/src/stt/stream_adapter.ts:74:27)"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"    at async STT.recognize (/app/node_modules/.pnpm/@livekit+agents@0.6.3_patch_hash=eq3w7j4u37gz34omjmrey44zca_@livekit+rtc-node@0.13.2/node_modules/@livekit/agents/src/stt/stt.ts:98:19)"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"    at async STT._recognize (/app/node_modules/.pnpm/@livekit+agents-plugin-openai@0.8.1_patch_hash=feaq6h6vsy43fwridxxhrfduka_@livekit+agents@0.6_l4pirnpcrrdzhnflugrwvoyql4/node_modules/@livekit/agents-plugin-openai/src/stt.ts:117:18)"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"    at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.79.4_ws@8.18.0_zod@3.24.1/node_modules/openai/src/core.ts:480:13)"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"APIConnectionError: Connection error."}
2025-01-23 11:39:05.939	
{"source":"stderr","log":""}
2025-01-23 11:39:05.939	
{"log":"","source":"stderr"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"            ^"}
2025-01-23 11:39:05.939	
{"source":"stderr","log":"      throw new APIConnectionError({ cause: response });"}
```

### PR DESCRIPTION
**Pull request by nbsp**
fixes #273

### CODE REVIEW

File: agents/src/stt/stream_adapter.ts [hunk 1]
```diff
@@ -71,13 +72,20 @@ export class StreamAdapterWrapper extends SpeechStream {
...
+              const event = await this.#stt.recognize(ev.frames);
+              if (!event.alternatives![0].text) {
+                continue;
+              }
+
+              this.output.put(event);
+              break;
+            } catch (error) {
+              log()
+                .child({ error: (error as Error).message })
```
Comment (lukasIO) [inline agents/src/stt/stream_adapter.ts]: do we want to lose all stack info here? 

also an `instanceof Error` seems preferable to casting it `as Error`

Comment (nbsp) [reply agents/src/stt/stream_adapter.ts]: the stack trace is gonna be `recognize -> _recognize -> (internal SDKs)`, so i don't think it's relevant here — this is in order to continue when an STT service 500s
