### PR TITLE
Fix: Race Condition When Participant Disconnects During STT/TTS Processing

### LINKED ISSUE #839: Race condition: "Queue is closed" error when participant disconnects during STT processing
### Describe the bug

Description:

  When a participant disconnects from a room, an unhandled error occurs in the STT (Speech-to-Text) processing pipeline,
  causing a "Queue is closed" error. While this appears to be harmless to the overall application flow, it generates error
  logs that shouldn't occur during normal operation.

  Steps to Reproduce:
  1. Start an agent session with STT enabled (using Deepgram/nova-3 in this case)
  2. Have a participant connect and engage in voice interaction
  3. Disconnect the participant while STT is actively processing

  Expected Behavior:
  The agent session should close cleanly when a participant disconnects, without throwing unhandled errors.

  Actual Behavior:
  An unhandled Queue is closed error is thrown when the STT stream attempts to process transcripts after the queue has been
  closed due to participant disconnect.

  Error Stack Trace:
  [14:56:24.373] ERROR (92972): Unhandled error. ({
    type: 'error',
    error: Error: Queue is closed
        at AsyncIterableQueue.put (/node_modules/@livekit/agents/src/utils.ts:275:13)
        at SpeechStream.processTranscript (/node_modules/@livekit/agents/src/inference/stt.ts:406:18)
        at recv (/node_modules/@livekit/agents/src/inference/stt.ts:348:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Task.fn (/node_modules/@livekit/agents/src/inference/stt.ts:369:11)
        at async run (/node_modules/@livekit/agents/src/utils.ts:433:14)

  Environment:
  - Package: @livekit/agents@1.0.17
  - STT Model: deepgram/nova-3
  - Node.js runtime
  - Platform: macOS (Darwin 24.6.0)

  Analysis:
  The error appears to be a race condition where:
  1. Participant disconnect triggers the agent session to close
  2. The AsyncIterableQueue is closed as part of cleanup
  3. In-flight STT processing attempts to put results into the now-closed queue
  4. This throws an unhandled error

The error appears harmless and doesn't affect functionality, but it pollutes logs and may mask other issues.

### Relevant log output

_No response_

### Describe your environment

 System:
    OS: macOS 15.6.1
    CPU: (8) arm64 Apple M1
    Memory: 410.16 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.9.0 - /Users/vkrishnaprasad/.nvm/versions/node/v23.9.0/bin/node
    npm: 10.9.2 - /Users/vkrishnaprasad/.nvm/versions/node/v23.9.0/bin/npm
    pnpm: 10.10.0 - /Users/vkrishnaprasad/.nvm/versions/node/v23.9.0/bin/pnpm
    bun: 1.0.35 - /Users/vkrishnaprasad/.bun/bin/bun
  npmPackages:
    @livekit/agents: ^1.0.18 => 1.0.18 
    @livekit/agents-plugin-cartesia: ~1.0.18 => 1.0.18 
    @livekit/agents-plugin-elevenlabs: ~1.0.18 => 1.0.18 
    @livekit/agents-plugin-livekit: ^1.0.18 => 1.0.18 
    @livekit/agents-plugin-silero: ^1.0.18 => 1.0.18 
    @livekit/noise-cancellation-node: ^0.1.9 => 0.1.9 

### Minimal reproducible example

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Devesh36**
This PR fixes a race condition that occurs when a participant disconnects from a room while STT or TTS processing is still running. Previously, in-flight processing attempted to write to the event queue after it had already been closed during teardown, resulting in unhandled “Queue is closed” errors in the logs. This update ensures clean shutdown behavior and prevents these benign but noisy errors.

## Changes Made

* Added defensive `if (!this.queue.closed)` checks and `try/catch` guards in `stt.ts` to ignore writes to closed queues.
* Updated `SynthesizeStream` in `tts.ts` to make `queue`, `closed`, and `abortController` public so plugins can safely check state before writing.
* Applied defensive queue handling across the following plugins to eliminate race conditions:

  * Deepgram (STT & TTS)
  * ElevenLabs (TTS)
  * OpenAI (TTS)
  * Cartesia (TTS)
  * Neuphonic (TTS)
* Updated the STT metrics monitoring loop to prevent errors when output queues close unexpectedly.
* Verified no functional regressions and ensured that disconnect flows complete cleanly.

## Pre-Review Checklist

* [x] **Build passes**: All builds (lint, typecheck, tests) pass locally
* [x] **AI-generated code reviewed**: Removed unnecessary comments and ensured code quality
* [x] **Changes explained**: All changes are properly documented and justified above
* [x] **Scope appropriate**: All changes relate to the PR title, or explanations provided for why they’re included
* [] **Video demo**: Verified functionality through a short demo using Agent Playground (if applicable)

## Testing

* Verified all packages and plugins compile using `pnpm -w -s build`.
* Confirmed defensive guards before all `queue.put()` calls in updated files.
* Ensured all automated tests pass.
* Manually tested both `restaurant_agent.ts` and `realtime_agent.ts` to confirm no regressions following core updates.

## Additional Notes

The “Queue is closed” error did not impact application logic but added unnecessary noise in logs. This PR ensures that teardown behavior is predictable and that these expected conditions no longer surface as unhandled errors.

---
/fix #839

### CODE REVIEW

File: agents/src/inference/stt.ts [hunk 1]
```diff
@@ -261,250 +224,232 @@ export class SpeechStream<TModel extends STTModels> extends BaseSpeechStream {
...
+        this.queue.put({
+          type: SpeechEventType.INTERIM_TRANSCRIPT,
+          requestId,
+          alternatives: [speechData],
+        });
+      }
+    } catch (e) {
+      // Silently ignore if queue was closed
+      if (e instanceof Error && !e.message.includes('Queue is closed')) {
+        this.#logger.error({ err: e }, 'Error putting transcript to queue');
```
Comment (toubatbrian) [inline agents/src/inference/stt.ts:521]: Should we make it warning level, since the error here is expected?

Comment (Devesh36) [reply agents/src/inference/stt.ts:521]: Done !!

**Comment by Devesh36** [comment]
> This is really nice, can you add a changeset as well?

Added that !

**Review by toubatbrian — APPROVED** [review]
